# Site settings
title: Daniel Hines
email: daniel.c.hines@vanderbilt.edu
url: https://danielchines.github.io
description: "A simple github pages website to display my resume and personal projects. Site created using Jekyll and the Freelancer Bootstrap theme."
skills: >
   Vanderbilt University '18  
   Computer Science and Engineering Management
meta_author: Daniel Hines

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
# contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 008b8b #5F9EA0 #008b8b
  primary-rgb: "0,139,139" #"0,139,139" #"128,179,255"
  secondary: 474e57 #FD6E8A #6495ED
  secondary-dark: 233140 #A2122F

# About section
about:
   p1: >
   I'm Daniel Hines, a senior computer science student and entrepreneur.
   I built this website directly into my <a href="https://github.com/danielchines/danielchines.github.io">Github repository</a> using GitHub's free static site hosting service, GitHub Pages. To format the site I used a little CSS and Bootstrap's Freelancer theme.
   I enjoy solving important problems and designing interfaces that make complex interactions as intuitive as possible.
# Footer settings
footer:
  copyright: Daniel Hines
  location: Vanderbilt University
  social: Visit my
  credits: Source Code

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/daniel-hines-b10483121/
  - title: facebook
    url: https://www.facebook.com/danny.hines.50
  - title: github
    url: http://github.com/danielchines

# Credits content
credits:
   credit: This site was created using the static site genereator <a href="https://jekyllrb.com/">Jekyll</a> and the <a href="https://startbootstrap.com/template-overviews/freelancer/">Freelancer</a> theme from <a href="http://startbootstrap.com">Bootstrap</a>.    
   sc: View the source code <a href="https://github.com/danielchines/danielchines.github.io">here</a>.

# Build settings
markdown: kramdown
permalink: pretty
