# Site settings
title: Daniel Hines
email: daniel.c.hines@vanderbilt.edu
url: https://danielchines.github.io
description: "A simple github pages website to display my resume and personal projects. Site created using Jekyll and the Freelancer Bootstrap theme."
skills: >
   Vanderbilt University '18  
   Computer Science and Engineering Management
meta_author: Daniel Hines

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
# contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 008b8b #5F9EA0 #008b8b
  primary-rgb: "0,139,139" #"0,139,139" #"128,179,255"
  secondary: 474e57 #FD6E8A #6495ED
  secondary-dark: 233140 #A2122F

# About section
about:
  p1: I'm Daniel Hines, a Chicago native and avid software/UX developer.
  p2: I originally used <a href="http://jmcglone.com/guides/github-pages/">this tutorial</a> to create a blog-based site using Github's free .io domain. To make it look less like craigslist I used <a href="https://github.com/jeromelachaud/freelancer-theme">this example</a> to implement a theme from Bootstrap, and added my own HTML/CSS/Javascript to make it look pretty. The source code is all in my <a href="https://github.com/danielchines/danielchines.github.io">repository</a> on Github.  
  p3: Two summers ago I used Coursera and Youtube tutorials to design, develop and publish a simple iOS puzzle game called The Next Level. Last summer I co-founded <a href="https://backme.com">BackMe Inc.</a>, a productivity-based app for iOS, where I'm developing the front-end UI for version 1.0 which will be available in late June.
  p4: Scroll down to view my past projects, which will be updated from my <a href="https://github.com/danielchines">Github</a> account. In the future I plan on delving into Ruby on Rails as well as Virtual Reality.

# Footer settings
footer:
  copyright: Daniel Hines
  location: Vanderbilt University
  social: Visit my
  credits: Source Code

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/daniel-hines-b10483121/
  - title: facebook
    url: https://www.facebook.com/danny.hines.50
  - title: github
    url: http://github.com/danielchines

# Credits content
credits:
   credit: This site was created using the static site genereator <a href="https://jekyllrb.com/">Jekyll</a> and the <a href="https://startbootstrap.com/template-overviews/freelancer/">Freelancer</a> theme from <a href="http://startbootstrap.com">Bootstrap</a>.    
   sc: View the source code <a href="https://github.com/danielchines/danielchines.github.io">here</a>.

# Build settings
markdown: kramdown
permalink: pretty
